### ISSUE TITLE
Add support for ox_target

### ISSUE THREAD

**Issue by johnsoul777** [GouveiaXS/angelicxs-YachtHeist#1]
Add support for ox_target

**Comment by johnsoul777** [comment]
https://overextended.github.io/docs/ox_target/Usage/Target

**Comment by GouveiaXS** [comment]
tests with exports.ox_target:removeZone() were unsuccessful.

**Comment by johnsoul777** [comment]
are you putting the ids? the id passed to removeZone is the return value from addBoxZone / addSphereZone.

**Comment by johnsoul777** [comment]
basically the name

**Comment by johnsoul777** [comment]
btw, no need to comment shared scripts, does qcore give problems with that?
