### ISSUE TITLE
Bug 3d text

### ISSUE THREAD

**Issue by johnsoul777** [GouveiaXS/angelicxs-YachtHeist#2]
3d text does not work on the yacht, it does on the ped

**Comment by johnsoul777** [comment]
![image](https://user-images.githubusercontent.com/72218928/205835586-62b186e9-6019-4f50-8e48-e075cc4ec305.png)

**Comment by GouveiaXS** [comment]
Fixed with the newest client update. Please update to the newest version.

**Comment by johnsoul777** [comment]
Thanks! I'll try it! you have my star
