### ISSUE TITLE
Bug Display 3d in Trolleys

### ISSUE THREAD

**Issue by johnsoul777** [GouveiaXS/angelicxs-YachtHeist#3]
![image](https://user-images.githubusercontent.com/72218928/206039923-7c91d5ad-a740-44c4-9d92-a0cea8b297f9.png)

**Comment by johnsoul777** [comment]
![image](https://user-images.githubusercontent.com/72218928/206040384-a0d8bc1d-1357-4c6a-a1ae-11248498662f.png)

**Comment by GouveiaXS** [comment]
Wrong variable was used in the check; new client version should now work.
